### ISSUE TITLE
Update license and copyright info in the source files

### ISSUE THREAD

**Issue by hsluoyz** [casbin-cpp/casbin-CMake-setup#3]
See: https://github.com/casbin/casbin-cpp/issues/203#issuecomment-1152868156

**Comment by hsluoyz** [comment]
@cs1137195420 can you work on this?

/cc @EmperorYP7

**Comment by cs1137195420** [comment]
> @cs1137195420 can you work on this?
> 
> /cc @EmperorYP7

Yes, of course. I' ve created https://github.com/casbin-cpp/casbin-CMake-setup/pull/6 for this issue. Does it meet the requirements of this issue?
